project:
  type: book

book:
  title: "Black Rock City Census 2023 Population Report"
  author: "Aaron \"Murrs\" Shev"
  date: "3/1/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - sociodemo.qmd
    - regionals_media_volunteering.qmd
    - perspectives.qmd
    - travel.qmd
    - camp_logistics.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

